FROM nvcr.io/nvidia/pytorch:19.09-py3

RUN pip install --upgrade pip
RUN pip install python-dotenv
#RUN pip install --upgrade https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
#RUN pip install --upgrade https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl
RUN pip install tb-nightly
RUN pip install future
RUN pip install seaborn
#RUN spacy download en
